package com.fatcloud.account.entity.order.enterprise

data class EnterpriseInfo(
    val accountId: String,
    val addr: String,
    val area: String,
    val bankNo: String,
    val bankPhone: String,
    val businessScope: List<Int>,
    val businessScopeNames: String,
    val createDt: String,
    val delFlag: Int,
    val enterpriseName0: String,
    val enterpriseName1: String,
    val enterpriseName2: String,
    val id: String,
    val income: Int,
    val investMoney: Int,
    val investYearNum: Int,
    val mold: String,
    val moldText: String,
    val money: Int,
    val nickName: String,
    val no: String,
    val payState: String,
    val payStateText: String,
    val productId: String,
    val productName: String,
    val productPriceId: Int,
    val productPriceName: String,
    val shareholders: List<Shareholder>,
    val state: String,
    val stateText: String,
    val updateDt: String,
    val username: String,
    val version: Int,
    val weixinPayMap: String
)