package com.fatcloud.account.entity.order.detail

data class BookkeepingDetail(
    val accountId: String = "",
    val businessLicenseImgUrl: String = "",
//    val businessScope: String = "",
    val businessScopeNames: String = "",
    val createDt: String = "",
    val id: String = "",
    val idno: String = "",
    val legalPersonName: String = "",
    val mold: String = "",
    val moldText: String = "",
    val money: String = "",
    val nickName: String = "",
    val no: String = "",
    val payState: String = "",
    val payStateText: String = "",
    val phone: String = "",
    val productId: String = "",
    val productName: String = "",
    val productPriceId: String = "",
    val productPriceName: String = "",
    val shopName: String = "",
    val signImgUrl: String = "",
    val state: String = "",
    val stateText: String = "",
    val updateDt: String = "",
    val username: String = ""
)